gpslab_geoip:
  # Path to download GeoIP database.
  # It's a default value. You can change it.
  cache: '%kernel.cache_dir%/GeoLite2-City.mmdb'

  # URL for download new GeoIP database.
  # It's a default value. You can change it.
  url: 'https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz'

  # Get model data in this locale
  # It's a default value. You can change it.
  locales: [ '%locale%' ]